version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      'discovery.type': 'single-node'
    ports:
    - 9200:9200
    - 9300:9300
  solr:
    image: redlinkgmbh/vind-solr-server:2.4.1
    ports:
    - 8983:8983
