language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  # Force caching of maven plugins used during deploy phase
  - mvn deploy:help versions:help help:help

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - chmod u+x .travis/trigger_deps.sh
  - if [ -n "$TRAVIS_TAG" ]; then .travis/trigger_deps.sh; fi

notifications:
  slack:
    secure: Si8uZ8P7cu3x4jXtcHnyhFDFfnqsnHqBwiYcCpDBRbJCsA4JkwbwdAUk2XgGFzvrdfxV1ifzC9BTD3EcHfq0Mt+OWJRcbXsRYFi2mMPEs+xkiW+JOsFSoZ0weiSLlBr5Gv9eZcVP/GwfaHDqbi/tOyKkytGmJTutBjoDrER97IYYxVmF/dqx1L8fKybYP8Gp6teLkZz/JzqU9B0AWBibKuSx8WiljQ71TTYOyFGJydhYgoAfBc4X9hsrxwLxQ2VzCOy9wJrNYLmROmA2nfeHkelCnyTBItKGMHRfGEcxr4b5BH8Cz40WhVGMNViw9VZ653JLMKsMVKDzn+2yJ82hajf8OVsubPtq/VyPAzJYJX0e2PPb2rx+CYqDij3FQdsYpU30l9eh+2VLgpBXxjx5Eiml9q0Mdt88I5Me2FJQRrSMRS82+lxIVRYGu/vUG4tM6PJ25TEWzrkY9KeytTGrSjVfsgirUkUKk7Ocvu58tpUe7D4Zxh+VEU6qRfetlMpCCIDxfXQ0bvCwr/KbMRYHvhiN6goOfRs8ixIORwMQRXSgmg/Ts7DFdmN7sEXsr4a6oHLAm4xxhjdgB3O6Nkweuy83FryNdQ7rGWSgb7XJVwrZ/ahZ9uBBGf16fbymOOAu/qnuAWcVjJdYz4hd1na5PsjKY8ffLGvZx7f7w7kfQBA=
